# Timeframe for the data if any it'll be last 5 years

# The format should be : 'YYYY-MM-DD'
date_begin:
date_end:

# Current Time Minus Time Pattern
# By hour: 'now #-H' only with (1-H and 4-H) By day : 'now #-d'
# and by month : 'today #-m' and if you want all the data : ''
date_pattern: 'today 3-m'

# Geo by default worldwide. If you want by country it's a 2 letters abbreviation example : FR, GB, US
# if you want a specific province : US-AL --> Alabama
geo: 'FR'


# Keyword list for your search no more than 5
terms: ['ASUS', 'ACER', 'MSI', 'RAZER', 'Alienware']
